#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x0294A902A6830C07 (indigo@keybase.io)
#
Name     : deprecated-pyflakes
Version  : 2.1.1
Release  : 57
URL      : https://files.pythonhosted.org/packages/52/64/87303747635c2988fcaef18af54bfdec925b6ea3b80bcd28aaca5ba41c9e/pyflakes-2.1.1.tar.gz
Source0  : https://files.pythonhosted.org/packages/52/64/87303747635c2988fcaef18af54bfdec925b6ea3b80bcd28aaca5ba41c9e/pyflakes-2.1.1.tar.gz
Source99 : https://files.pythonhosted.org/packages/52/64/87303747635c2988fcaef18af54bfdec925b6ea3b80bcd28aaca5ba41c9e/pyflakes-2.1.1.tar.gz.asc
Summary  : passive checker of Python programs
Group    : Development/Tools
License  : MIT
Requires: deprecated-pyflakes-bin = %{version}-%{release}
Requires: deprecated-pyflakes-license = %{version}-%{release}
Requires: deprecated-pyflakes-python = %{version}-%{release}
BuildRequires : buildreq-distutils
BuildRequires : buildreq-distutils3
BuildRequires : python-core
BuildRequires : setuptools-legacypython

%description
========
Pyflakes
========
A simple program which checks Python source files for errors.

%package bin
Summary: bin components for the deprecated-pyflakes package.
Group: Binaries
Requires: deprecated-pyflakes-license = %{version}-%{release}

%description bin
bin components for the deprecated-pyflakes package.


%package legacypython
Summary: legacypython components for the deprecated-pyflakes package.
Group: Default
Requires: python-core

%description legacypython
legacypython components for the deprecated-pyflakes package.


%package license
Summary: license components for the deprecated-pyflakes package.
Group: Default

%description license
license components for the deprecated-pyflakes package.


%package python
Summary: python components for the deprecated-pyflakes package.
Group: Default

%description python
python components for the deprecated-pyflakes package.


%prep
%setup -q -n pyflakes-2.1.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1554340968
export MAKEFLAGS=%{?_smp_mflags}
python2 setup.py build -b py2

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/deprecated-pyflakes
cp LICENSE %{buildroot}/usr/share/package-licenses/deprecated-pyflakes/LICENSE
python2 -tt setup.py build -b py2 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
%exclude /usr/bin/pyflakes

%files legacypython
%defattr(-,root,root,-)
/usr/lib/python2*/*

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/deprecated-pyflakes/LICENSE

%files python
%defattr(-,root,root,-)
